Add ir.a target in Makefile
dstogov/ir pull request #27
Opened 2023-05-03 02:22 UTC by tekknolagi

This makes it easier to use as a library:

  $ make ir.a
  ...
  $ gcc test.c ir.a -o test
  $ ./test
  :)
  $

2023-05-03 07:56 UTC, dstogov requested changes
@tekknolagi thanks for the proposal.

We didn't think about distribution this like a library yet. Currently we use IR in a new generation JIT for PHP and embed the necessary IR source files through the PHP build system.

I agree, the library may be helpful for others.
I think, we may accept this, if we start using ``ir.a`` to build ``ir`` and ``ir_test``.
Similar thing should be done for Windows (may be not in the same PR).
Than ``Makefile`` may be extended with ``install`` and ``uninstall`` targets.

CC @weltling

2023-05-03 21:43 UTC, tekknolagi commented
I may look into this -- thanks

2023-05-03 21:58 UTC, weltling commented on Makefile
> +$(BUILD_DIR)/ir.a: $(OBJS_COMMON)
Usually the name should be prefixed with `lib`, eg. `libir.a`.

thanks

2023-05-03 22:43 UTC, weltling commented
> I agree, the library may be helpful for others.
> I think, we may accept this, if we start using `ir.a` to build `ir` and `ir_test`.

Ditto. Switching to depend on the `.a` target instead ob `.o` targets should be done in the same PR, so then still both types of artifacts are validated.

Btw, this still wouldn't exclude offering a way of drop-in sources, but i guess we can also see to package a source archive suitable for that, or maybe have a doc on how to embed sources. 

> Than `Makefile` may be extended with `install` and `uninstall` targets.

Looking at this, one could still say for these purposes having something like a dedicated `cmake` defs would serve better? While the `Makefile` is simple and quick for the development, delivering libraries and headers, plus handling dependencies, would be still better served by something more powerful. In the end, we might still end up producing dynamic libs as well, split debug info, etc.

Thanks

2024-03-13 20:36 UTC, dstogov commented
Merged as a part of https://github.com/dstogov/ir/pull/75

2024-03-13 20:36 UTC, closed without merging

2024-03-13 21:14 UTC, tekknolagi commented
Cool!